Repository pagopa/pagopa-receipt-pdf-notifier, pull requests merged in 2023-08, with the labels that each got.

#22 [PRDP-85] fix: Added info response body with services info
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/AppInfo.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/InfoTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/util/HttpResponseMessageMock.java
  src/test/resources/META-INF/maven/it.gov.pagopa.receipt.pdf.notifier/pagopa-receipt-pdf-notifier/pom.properties
Labels: bug, patch, size/small

#21 fix: Updated run_docker.sh to properly check info status code
  docker/run_docker.sh
Labels: bug, size/small

#23 [PRDP-85] fix: Info endpoint response
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.receipt.pdf.notifier/pagopa-receipt-pdf-notifier/pom.properties
Labels: bug, patch, size/small

#24 fix: Identity
  .identity/02_application_action.tf
Labels: size/small

#25 [PRDP-38] feat: Add performance tests
  .devops/performance-test-pipelines.yml
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/datastore_client.js
  performance-test/src/receipt_processor.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
Labels: enhancement, size/large, patch

#27 fix: Aks limits
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#28 [PRDP-117] feat:Added slack webhook to integration test action
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: enhancement, minor, size/small

#30 [fix] Fixed integration-test action notification
  .github/workflows/integration_test.yml
Labels: patch, size/small, skip

#31 Update for performance test
  helm/values-uat.yaml
  performance-test/src/test-types/constant.json
Labels: size/small, skip
