Repository pagopa/pagopa-receipt-pdf-notifier, pull requests merged in 2023-09, with the labels that each got.

#34 fix: Upd helm chart
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
Labels: patch, size/small

#32 feat: Update for performance test
  performance-test/src/uat.environment.json
Labels: size/small

#36 [PRDP-133] feat: Add slf4j and otl agent
  Dockerfile
  agent/config.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetry.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/NotifierRetryTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
Labels: enhancement, minor

#37 fix: Increase memory request and limit
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, size/small, skip

#39 [PRDP-123] feat: Use deployment selfhosted runner for integration test
  .github/workflows/integration_test.yml
  integration-test/src/package.json
Labels: enhancement, size/small, skip

#38 [PRDP-133] fix: Change log service name
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/logback.xml
Labels: bug, patch, size/small

#40 [PRDP-135] Added receipt's timestamps
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
Labels: enhancement, minor, size/small

#41 fix: Deploy
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#42 [feat] Lowered max replica to 1
  helm/values-uat.yaml
Labels: enhancement, size/small
