Repository pagopa/pagopa-receipt-pdf-notifier, pull requests merged in 2023-07, with the labels that each got.

#4 feat: add identity and upd gha pipe
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release-deploy.yml
  .github/workflows/sonar_analysis.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: size/large

#6 [PRDP-45] chore: updated UAT helm values
  helm/values-uat.yaml
Labels: patch, size/small

#11 [PRDP-37] feat: add integration tests
  .env.example
  .github/workflows/code_review.yml
  .gitignore
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  README.md
  docker/README.md
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/config/properties.json
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipt_queue_client.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  local.settings.json.example
Labels: enhancement, size/large, skip

#12 chore: change log levels
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
Labels: patch, size/small

#13 fix: subject and markdown
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: size/small

#14 fix2 : markdown
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: size/small

#16 fix: try4
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: size/small

#18 fix: Notify message response
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ErrorToNotifyException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
Labels: bug, patch, size/small

#19 [feat-remove-canary] Removed canary deploy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#20 fix: Gha runner
  .github/workflows/deploy_with_github_runner.yml
Labels: size/small
