Repository pagopa/pagopa-receipt-pdf-notifier, pull requests merged in 2023-10, with the labels that each got.

#46 feat: Update helm uat
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#44 feat: updated ReceiptToIOServiceImpl to log unable to send status
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
Labels: patch, size/small

#43 [PRDP-104] feat: Integrate subject and markdown
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/NotifierQueueClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/EventData.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/MissingFieldsForNotificationException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/IOMessageService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ObjectMapperUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIOTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/ReceiptQueueClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/utils/ObjectMapperUtilsTest.java
  src/test/resources/logback-test.xml
Labels: enhancement, size/large, minor

#49 [PRDP-153] fix: Update receipt model
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  performance-test/src/modules/common.js
Labels: size/small, ignore-for-release

#55 [PRDP-159] Deleted fiscal code from logs
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
Labels: enhancement, patch, size/small

#56 [PRDP-157] fix: Removed base64 encoding
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
Labels: bug, patch, size/small

#57 chore: Enabled IO
  helm/values-uat.yaml
Labels: size/small

#59 [PRDP-157] fix: Notification message special characters
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, patch, size/small

#60 [PRDP-166] feat: Amount in italian format
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
Labels: enhancement, patch, size/small

#58 chore: remove otl agent from prod configuration
  helm/values-prod.yaml
Labels: bug, size/small, skip

#63 [fix-currency-format] fix: Changed currency format
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
Labels: patch, size/small

#64 [PRDP-164] feat: Improve error messages
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/message/IOMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/ReasonError.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
Labels: minor

#67 chore: Upd helm prod
  helm/values-prod.yaml
Labels: size/small

#68 [PRDP-193] feat: Upgrade java version to jdk 17
  .github/maven_code_review/action.yml
  .github/workflows/code_review.yml
  Dockerfile
  docker/docker-compose.yml
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
Labels: enhancement, minor, size/small
