Repository pagopa/pagopa-receipt-pdf-notifier, pull requests merged in 2023-11, with the labels that each got.

#70 [PRDP-190] feat: Integrate PDV Tokenizer
  .github/workflows/integration_test.yml
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/step_definitions/common.js
  performance-test/src/modules/common.js
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/PDVTokenizerClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ErrorToNotifyException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/PDVTokenizerException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/PDVTokenizerUnexpectedException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/exception/ReceiptNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/ErrorMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/ErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/InvalidParam.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/PiiResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/model/tokenizer/TokenResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/PDVTokenizerService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/PDVTokenizerServiceRetryWrapper.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceRetryWrapperImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceRetryWrapperImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
Labels: enhancement, size/large, minor

#72 chore: Fix double quote
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#73 fix: Tokenizer error response mapping
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/PDVTokenizerServiceImpl.java
Labels: patch, size/small

#76 chore: Update reason error status codes
  docker/run_docker.sh
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/enumeration/ReasonErrorCode.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/client/impl/PDVTokenizerClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImplTest.java
Labels: size/small

#75 [PRDP-198] feat: Make subject field not mandatory
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/IOMessageServiceImplTest.java
Labels: enhancement, patch, size/small

#77 feat: Add health function
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/Health.java
  src/test/java/it/gov/pagopa/receipt/pdf/notifier/HealthTest.java
Labels: enhancement, patch, size/small

#80 feat: introducing parallelized stream in ReceiptToIO
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: minor, size/small

#82 Revert "feat: introducing parallelized stream in ReceiptToIO"
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/ReceiptToIOService.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/service/impl/ReceiptToIOServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: size/small

#83 feat: Introducing parallel stream
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/ReceiptToIO.java
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/utils/ReceiptToIOUtils.java
Labels: patch, size/small

#87 [PRDP-258] Added new Receipt status TO_REVIEW
  src/main/java/it/gov/pagopa/receipt/pdf/notifier/entity/receipt/enumeration/ReceiptStatusType.java
Labels: patch, size/small
